/**********************************************************/
/* Automatically generated by './mkconfig': do note edit! */
/**********************************************************/
#define LGL_OS "Linux vvv-dejavu 5.7.7-arch1-1 x86_64"
#define LGL_COMPILED "Mon  6 Jul 20:10:18 CEST 2020"
#define LGL_RELEASED "Sat Oct 13 14:05:26 CEST 2012"
#define LGL_VERSION "ala"
#define LGL_ID "b02aa1a04343558c4252b5f4a723be021964f652"
